---

- name: "Create AWS config directory"
  file:
    path: "{{ aws_config_directory }}"
    state: directory
    owner: "{{ cloud_user }}"
    group: "{{ cloud_user }}"

- name: "Transfer local AWS config"
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: "{{ cloud_user }}"
    group: "{{ cloud_user }}"
  loop: "{{ aws_config_files }}"

- name: "Install pip packages"
  pip:
    name: "{{ item }}"
  loop: "{{ aws_pip_packages }}"
