---

- name: "Transfer local AWS config"
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop:
  -
    src: "~/.aws/credentials"
    dst: "{{ home }}/.aws/credentials"
  -
    src: "~/.aws/config"
    dst: "{{ home }}/.aws/config"

- name: "Install pip"
  yum:
    name: "python2-pip"
    state: present

- name: "Install pip packages"
  pip:
    name: "{{ item }}"
  loop:
  - "awscli"
  - "boto"
  - "boto3"
  - "botocore"
  - "s3transfer"
