---

- name: "Provision Bastion Base Image"
  hosts: packer
  become: true
  become_method: sudo
  become_user: root
  vars:
    home     : "/home/centos"
    pem_file : "~/.ssh/k8s-key.pem"
  tasks:
  -
    name: "Locale environment settings"
    copy:
      content: |
        LANG=en_GB.utf-8
        LC_ALL=en_GB.utf-8
      dest: "/etc/environment"
  -
    name: "Install Bastion Packages"
    yum:
      name: "{{ item }}"
      state: present
    loop:
    - "epel-release"
    - "ansible"
    - "wget"
    - "curl"
    - "git"
    - "vim"
    - "net-tools"
    - "bind-utils"
    - "iptables-services"
    - "bridge-utils"
    - "bash-completion"
    - "firewalld"
    - "python2-pip"
  -
     name: "Upgrade pip to latest"
     pip:
       name: "pip"
       state: latest
  -
     name: "Install pip packages"
     pip:
       name: "{{ item }}"
     loop:
     - "awscli"
     - "boto"
     - "boto3"
     - "botocore"
     - "s3transfer"
  -
    name: "Create config directories in centos home directory"
    file:
      path: "{{ item }}"
      state: directory
    loop:
    - "{{ home }}/.ssh"
    - "{{ home }}/.aws"
  -
    name: "Copy PEM to bastion"
    copy:
      src: "{{ pem_file }}"
      dest: "{{ home }}/.ssh/key.pem"
      owner: centos
      group: centos
      mode: 0400
  -
     name: "Copy SSH keys"
     copy:
       src: "~/.ssh/{{ item.name }}"
       dest: "{{ home }}/.ssh/{{ item.name }}"
       mode: "{{ item.permissions }}"
     loop:
     -
       name: "id_rsa"
       permissions: '600'
     -
       name: "id_rsa.pub"
       permissions: '644'
  -
     name: "Add the ssh key to the agent"
     shell: |
       eval $(ssh-agent -s)
       ssh-add {{ home }}/.ssh/id_rsa
  -
    name: "Copy AWS credentials for dynamic inventory"
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
    loop:
    -
      src: "~/.aws/credentials"
      dst: "{{ home }}/.aws/credentials"
    -
      src: "~/.aws/config"
      dst: "{{ home }}/.aws/config"
  -
    name: "Set SSH config"
    copy:
      content: |
        Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            IdentityFile ~/.ssh/key.pem
      dest: "{{ home }}/.ssh/config"
