---

- name: "Provision Kubernetes Base Image"
  hosts: packer
  become: true
  become_method: sudo
  become_user: root
  tasks:
  -
    name: "Locale environment settings"
    copy:
      content: |
        LANG=en_GB.utf-8
        LC_ALL=en_GB.utf-8
      dest: "/etc/environment"
  -
    name: "Turn off yum caching"
    lineinfile:
      path: "/etc/yum.conf"
      regexp: "^http_caching="
      line: "http_caching=none"
  -
    name: "Set selinux to permissive mode"
    selinux:
      policy: "targeted"
      state: "permissive"
  -
    name: "Install useful packages"
    yum:
      name: "{{ item }}"
      state: present
    loop:
    - "wget"
    - "git"
    - "vim"
    - "net-tools"
    - "bind-utils"
    - "iptables-services"
    - "bridge-utils"
    - "bash-completion"
    - "firewalld"
  -
    name: "Start firewalld"
    systemd:
      name: "firewalld"
      enabled: yes
      state: started
  -
    name: "Required kernel modules to be loaded"
    modprobe:
      name: "{{ item }}"
      state: present
    loop:
    - "overlay"
    - "br_netfilter"
  -
    name: "Make sure iptables is not bypassed and is persistent"
    copy:
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
      dest: "/etc/sysctl.d/99-kubernetes-cri.conf"
  -
    name: "Reload sysctl"
    shell: "sysctl --system"
  -
    name: "Add CRI-O yum repositry"
    yum_repository:
      name: "cri-o"
      description: "CRI-O repository"
      baseurl: "https://cbs.centos.org/repos/paas7-crio-311-candidate/x86_64/os/"
      enabled: yes
      gpgcheck: no
      repo_gpgcheck: no
  -
    name: "Install CRI-O"
    yum:
      name: "cri-o"
      state: present
  -
    name: "Ensure CRI-O is enabled"
    systemd:
      name: "crio"
      enabled: yes
  -
    name: "Ensure kubernetes repo is enabled"
    yum_repository:
      name: "kubernetes"
      description: "kubernetes install packages"
      baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey:
      - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
      - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
      exclude:
      - "kube*"
  -
    name: "Install kubernetes packages"
    yum:
      name: "{{ item }}"
      state: present
      disable_excludes: "kubernetes"
    loop:
    - "kubelet"
    - "kubeadm"
    - "kubectl"
  -
    name: "Enable kubelet"
    systemd:
      name: "kubelet"
      enabled: yes
