---

- name: "Ensure kubernetes repo is enabled"
  yum_repository:
    name: "kubernetes"
    description: "kubernetes install packages"
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
    - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
    - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
    exclude:
    - "kube*"

- name: "Install kubernetes packages"
  yum:
    name: "{{ item }}"
    state: present
    disable_excludes: "kubernetes"
  loop:
  - "kubelet-{{ kubernetes_version}}"
  - "kubeadm-{{ kubernetes_version }}"
  - "kubectl-{{ kubernetes_version }}"

- name: "Create systemd service drop-in folder for kubelet"
  file:
    path: "/etc/systemd/system/kubelet.service.d"
    state: directory

- name: "Start the kubelet"
  systemd:
    name: "kubelet"
    enabled: yes
    state: started

- name: "Pre-pull kubernets images"
  shell: "kubeadm config images pull"
