---

- name: "Required kernel modules to be loaded"
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
  - "overlay"
  - "br_netfilter"

- name: "Make sure iptables is not bypassed and is persistent"
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
    dest: "/etc/sysctl.d/99-kubernetes-cri.conf"

- name: "Create systemd service drop-in folder for kubelet"
  file:
    path: "/etc/systemd/system/kubelet.service.d"
    state: directory

- name: "Reload sysctl"
  shell: "sysctl --system"
