---

- name: "Provision Kubernetes Base Image"
  hosts: packer
  become: yes
  become_method: sudo
  become_user: root
  roles:
  - role: "common"
  - role: "firewall"
  - role: "kubernetes"
