---

- name: "Map node type to file name"
  set_fact:
    file_name: "{{ hostvars[inventory_hostname].host_type }}"

- name: "Load firewall rules"
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ file_name }}.yml"
  - "default.yml"

- name: "Configure firewall rules"
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ firewall_rules }}"
  when: firewall_rules
  notify:
  - reload-firewall
  - restart-firewall
