---

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    role_groups:
        master:
        - "nodes"
        - "masters"
        - "kubernetes"
        bastion:
        - "nodes"
        - "bastion"
        worker:
        - "nodes"
        - "workers"
        - "kubernetes"
  tasks:
  -
    name: "Gather instances facts"
    ec2_instance_facts:
    register: facts
  -
    name: "Add hosts and groups"
    include_tasks: "./add-host.yml"
    vars:
       host_facts: "{{ item }}"
    loop: "{{ facts.instances }}"
  - 
    name: "Add first master group"
    add_host:
      hostname: "{{ groups.masters.0 }}"
      groups: "first_master"
