---

aws_config_directory: "{{ cloud_home }}/.aws"

aws_config_files:
-
  src: "~/.aws/credentials"
  dst: "{{ aws_config_directory }}/credentials"
-
  src: "~/.aws/config"
  dst: "{{ aws_config_directory }}/config"

aws_pip_packages:
- "awscli"
- "boto"
- "boto3"
- "botocore"
- "s3transfer"
